import type { Metadata } from 'next';
import Link from 'next/link';

import { DrawdownChart, LineChart } from '@/components/charts';
import { PaperBadge } from '@/components/disclaimer';
import { Card, DefinitionList, Freshness, Metric, PageHeader } from '@/components/page';
import { DegradedBanner, EmptyState, ErrorState } from '@/components/states';
import {
  formatCount,
  formatMoney,
  formatNumber,
  formatPercent,
  formatPrice,
  formatSignedMoney,
  formatSignedPercent,
  formatTimestamp,
  humanizeEnum,
  isZeroTime,
  list,
} from '@/lib/format';
import { api } from '@/lib/server/api';
import { platformStatus } from '@/lib/server/platform';

export const metadata: Metadata = { title: 'Paper trading' };
export const dynamic = 'force-dynamic';

export default async function PaperTradingPage() {
  const client = api();
  const [platform, portfolioR, positionsR, ordersR] = await Promise.all([
    platformStatus(),
    client.portfolio(),
    client.positions(),
    client.orders({ limit: 100 }),
  ]);

  const pf = portfolioR.ok ? portfolioR.data.portfolio : null;
  const curve = portfolioR.ok ? list(portfolioR.data.equity_curve) : [];
  const trades = portfolioR.ok ? list(portfolioR.data.trades) : [];
  const positions = positionsR.ok ? list(positionsR.data) : [];
  const orders = ordersR.ok ? list(ordersR.data) : [];

  return (
    <>
      <PageHeader
        title="Paper trading"
        purpose="The simulated portfolio. Every fill below is generated by the simulator against modelled costs and slippage — no order in this platform reaches a broker, an exchange, or any real-money venue."
      >
        <div
          role="note"
          className="flex flex-wrap items-center gap-3 rounded-md border-2 border-ink-900 bg-ink-100 px-4 py-3"
        >
          <PaperBadge />
          <p className="max-w-prose text-sm font-medium leading-snug text-ink-900">
            Everything on this page is simulated. Positions, fills, P&amp;L and
            returns are the output of a simulator; they are not a record of
            anything that happened in a market, and they are not a statement about
            what would have happened.
          </p>
        </div>
      </PageHeader>

      <div className="mt-4 space-y-4">
        <DegradedBanner
          degraded={platform.degraded}
          ready={platform.readiness.ready}
          reason={platform.readiness.reason}
        />

        <Card
          title="Simulated portfolio"
          actions={<Freshness servedAt={portfolioR.ok ? portfolioR.servedAt : undefined} meta={portfolioR.ok ? portfolioR.meta : undefined} />}
        >
          {!portfolioR.ok ? (
            <ErrorState error={portfolioR} what="the paper portfolio" />
          ) : !pf ? (
            <EmptyState title="No portfolio was returned." />
          ) : (
            <div className="space-y-4">
              {!pf.paper ? (
                <p role="alert" className="rounded border border-deny bg-red-50 px-3 py-2 text-sm font-semibold text-deny">
                  <span aria-hidden="true">✕ </span>
                  This portfolio is not flagged as paper. That contradicts the
                  platform&apos;s guarantee that no real-money counterpart exists —
                  treat this record as suspect and do not act on it.
                </p>
              ) : null}

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <Metric
                  label="Simulated equity"
                  value={formatMoney(pf.equity)}
                  sub={<PaperBadge />}
                />
                <Metric label="Simulated cash" value={formatMoney(pf.cash)} />
                <Metric
                  label="Simulated total P&L"
                  value={formatSignedMoney(pf.total_pnl)}
                  sub={
                    <span className={pf.total_pnl >= 0 ? 'text-allow' : 'text-deny'}>
                      <span aria-hidden="true">{pf.total_pnl >= 0 ? '▲ ' : '▼ '}</span>
                      {formatSignedPercent(pf.return_pct)}
                    </span>
                  }
                  hint="Simulated. Not a return anyone earned."
                />
                <Metric
                  label="Drawdown"
                  value={formatPercent(pf.drawdown)}
                  sub={<span>max {formatPercent(pf.max_drawdown)}</span>}
                />
              </div>

              <DefinitionList
                columns={3}
                items={[
                  { term: 'Starting cash', value: formatMoney(pf.starting_cash) },
                  { term: 'Market value', value: formatMoney(pf.market_value) },
                  { term: 'Realized P&L', value: formatSignedMoney(pf.realized_pnl) },
                  { term: 'Unrealized P&L', value: formatSignedMoney(pf.unrealized_pnl) },
                  { term: 'Gross exposure', value: formatMoney(pf.gross_exposure) },
                  { term: 'Net exposure', value: formatMoney(pf.net_exposure) },
                  { term: 'Long exposure', value: formatMoney(pf.long_exposure) },
                  { term: 'Short exposure', value: formatMoney(pf.short_exposure) },
                  { term: 'Leverage', value: formatNumber(pf.leverage, 2) },
                  { term: 'Peak equity', value: formatMoney(pf.peak_equity) },
                  { term: 'Currency', value: pf.currency || '—' },
                  { term: 'As of', value: formatTimestamp(pf.as_of) },
                ]}
              />

              {Object.keys(pf.sector_exposure ?? {}).length > 0 ? (
                <div>
                  <h3 className="mb-1.5 text-xs font-bold uppercase tracking-wide text-ink-600">
                    Sector exposure
                  </h3>
                  <ul className="flex flex-wrap gap-2">
                    {Object.entries(pf.sector_exposure ?? {}).map(([sector, v]) => (
                      <li
                        key={sector}
                        className="rounded border border-ink-200 bg-ink-50 px-2 py-1 text-xs"
                      >
                        {sector}: <span className="num font-medium">{formatPercent(v)}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </div>
          )}
        </Card>

        <Card title="Simulated equity curve" subtitle="Simulated equity and drawdown over the run.">
          {curve.length === 0 ? (
            <EmptyState
              title="No equity curve"
              detail="The curve is sampled as the simulator runs. With no fills yet there is nothing to plot — which is different from a flat line at zero."
            />
          ) : (
            <div className="space-y-3">
              <LineChart
                points={curve
                  .filter((p) => !isZeroTime(p.at))
                  .map((p) => ({ x: Date.parse(p.at), y: p.equity }))
                  .sort((a, b) => a.x - b.x)}
                label="Simulated equity"
                yFormat={(v) => formatMoney(v)}
                xFormat={(v) => new Date(v).toISOString().slice(11, 16)}
                baseline={pf?.starting_cash}
                area
              />
              <p className="text-[11px] text-ink-500">
                The dashed line is starting cash. Simulated result — no capital was
                at risk.
              </p>
              <DrawdownChart
                points={curve
                  .filter((p) => !isZeroTime(p.at))
                  .map((p) => ({ x: Date.parse(p.at), y: p.drawdown }))
                  .sort((a, b) => a.x - b.x)}
                label="Simulated drawdown"
              />
            </div>
          )}
        </Card>

        <Card
          title="Open simulated positions"
          actions={<Freshness servedAt={positionsR.ok ? positionsR.servedAt : undefined} meta={positionsR.ok ? positionsR.meta : undefined} />}
        >
          {!positionsR.ok ? (
            <ErrorState error={positionsR} what="positions" />
          ) : positions.length === 0 ? (
            <EmptyState
              title="No open simulated positions"
              detail="Positions open when a simulated order fills. No signals have produced a fill, or the broker has not been given any orders."
            />
          ) : (
            <div className="table-wrap">
              <table className="data-table">
                <caption className="sr-only">
                  Open simulated positions. All values are simulator output.
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Avg price</th>
                    <th scope="col">Market price</th>
                    <th scope="col">Market value</th>
                    <th scope="col">Unrealized P&L</th>
                    <th scope="col">Realized P&L</th>
                    <th scope="col">Opened</th>
                  </tr>
                </thead>
                <tbody>
                  {positions.map((p) => (
                    <tr key={`${p.ticker}-${p.opened_at}`}>
                      <th scope="row">
                        <Link href={`/stock/${encodeURIComponent(p.ticker)}`} className="link">
                          {p.ticker}
                        </Link>
                        {p.sector ? (
                          <span className="block text-[11px] font-normal text-ink-500">
                            {p.sector}
                          </span>
                        ) : null}
                      </th>
                      <td className="num">
                        {formatNumber(p.quantity, 0)}
                        <span className="ml-1 text-[10px] font-semibold text-ink-500">
                          {p.quantity < 0 ? 'SHORT' : 'LONG'}
                        </span>
                      </td>
                      <td className="num">{formatPrice(p.avg_price)}</td>
                      <td className="num">{formatPrice(p.market_price)}</td>
                      <td className="num">{formatMoney(p.market_value)}</td>
                      <td className={`num font-medium ${p.unrealized_pnl >= 0 ? 'text-allow' : 'text-deny'}`}>
                        <span aria-hidden="true">{p.unrealized_pnl >= 0 ? '▲ ' : '▼ '}</span>
                        {formatSignedMoney(p.unrealized_pnl)}
                      </td>
                      <td className="num">{formatSignedMoney(p.realized_pnl)}</td>
                      <td className="num whitespace-nowrap text-xs text-ink-600">
                        {formatTimestamp(p.opened_at)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>

        <Card
          title="Simulated orders"
          actions={<Freshness servedAt={ordersR.ok ? ordersR.servedAt : undefined} meta={ordersR.ok ? ordersR.meta : undefined} />}
        >
          {!ordersR.ok ? (
            <ErrorState error={ordersR} what="orders" />
          ) : orders.length === 0 ? (
            <EmptyState
              title="No simulated orders"
              detail="Orders are submitted with an idempotency key so submission is safe to retry. None have been submitted in this run."
            />
          ) : (
            <div className="table-wrap">
              <table className="data-table min-w-[52rem]">
                <caption className="sr-only">
                  Simulated orders, newest first. No order reaches a real venue.
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Side</th>
                    <th scope="col">Type</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Status</th>
                    <th scope="col">Filled</th>
                    <th scope="col">Avg fill</th>
                    <th scope="col">Commission</th>
                    <th scope="col">Slippage</th>
                    <th scope="col">Created</th>
                  </tr>
                </thead>
                <tbody>
                  {orders.map((o) => (
                    <tr key={o.id}>
                      <th scope="row">
                        <Link href={`/stock/${encodeURIComponent(o.ticker)}`} className="link">
                          {o.ticker}
                        </Link>
                      </th>
                      <td>
                        <span
                          className={`inline-flex items-center gap-1 rounded border px-1.5 py-0.5 text-[10px] font-bold ${
                            o.side === 'BUY'
                              ? 'border-up bg-teal-50 text-up'
                              : 'border-down bg-red-50 text-down'
                          }`}
                        >
                          <span aria-hidden="true">{o.side === 'BUY' ? '▲' : '▼'}</span>
                          {o.side}
                        </span>
                      </td>
                      <td className="text-xs">{o.type}</td>
                      <td className="num">{formatNumber(o.quantity, 0)}</td>
                      <td className="text-xs">
                        <span
                          className={
                            o.status === 'REJECTED'
                              ? 'font-semibold text-deny'
                              : o.status === 'FILLED'
                                ? 'font-semibold text-allow'
                                : 'text-ink-700'
                          }
                        >
                          {humanizeEnum(o.status)}
                        </span>
                        {o.reject_reason ? (
                          <span className="block max-w-[14rem] text-[11px] leading-snug text-ink-500">
                            {o.reject_reason}
                          </span>
                        ) : null}
                      </td>
                      <td className="num">{formatNumber(o.filled_qty, 0)}</td>
                      <td className="num">{formatPrice(o.avg_fill_price)}</td>
                      <td className="num">{formatMoney(o.commission)}</td>
                      <td className="num">{formatNumber(o.slippage_bps, 1)} bps</td>
                      <td className="num whitespace-nowrap text-xs text-ink-600">
                        {formatTimestamp(o.created_at)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>

        <Card title="Simulated round trips" subtitle={`${formatCount(trades.length)} completed.`}>
          {trades.length === 0 ? (
            <EmptyState title="No round trips have completed." />
          ) : (
            <div className="table-wrap">
              <table className="data-table min-w-[48rem]">
                <caption className="sr-only">Completed simulated round trips.</caption>
                <thead>
                  <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Side</th>
                    <th scope="col">Entry</th>
                    <th scope="col">Exit</th>
                    <th scope="col">Qty</th>
                    <th scope="col">P&L</th>
                    <th scope="col">Return</th>
                    <th scope="col">Costs</th>
                    <th scope="col">Regime</th>
                    <th scope="col">Exit reason</th>
                  </tr>
                </thead>
                <tbody>
                  {trades.map((t, i) => (
                    <tr key={i}>
                      <th scope="row">{t.ticker}</th>
                      <td className="text-xs">{t.side}</td>
                      <td className="num text-xs">
                        {formatPrice(t.entry_price)}
                        <span className="block text-[10px] text-ink-500">
                          {formatTimestamp(t.entry_at)}
                        </span>
                      </td>
                      <td className="num text-xs">
                        {formatPrice(t.exit_price)}
                        <span className="block text-[10px] text-ink-500">
                          {formatTimestamp(t.exit_at)}
                        </span>
                      </td>
                      <td className="num">{formatNumber(t.quantity, 0)}</td>
                      <td className={`num font-medium ${t.pnl >= 0 ? 'text-allow' : 'text-deny'}`}>
                        <span aria-hidden="true">{t.pnl >= 0 ? '▲ ' : '▼ '}</span>
                        {formatSignedMoney(t.pnl)}
                      </td>
                      <td className="num">{formatSignedPercent(t.return_pct)}</td>
                      <td className="num">{formatMoney(t.costs)}</td>
                      <td className="text-xs">{t.regime ? humanizeEnum(t.regime) : '—'}</td>
                      <td className="text-xs text-ink-600">{t.exit_reason}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>
      </div>
    </>
  );
}
